// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXuwbpVjTtraQAnr7Fle6yrzKC2TpYvJY',
    appId: '1:197971236822:web:26cbb03d2b4c3f01fc3677',
    messagingSenderId: '197971236822',
    projectId: 'project-rohan-ad72e',
    authDomain: 'project-rohan-ad72e.firebaseapp.com',
    storageBucket: 'project-rohan-ad72e.firebasestorage.app',
    measurementId: 'G-Q595TX1J24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbckR0PGHbBBpse1iW1LLtDQBfi7BhMkI',
    appId: '1:197971236822:android:ea136ce4716b52edfc3677',
    messagingSenderId: '197971236822',
    projectId: 'project-rohan-ad72e',
    storageBucket: 'project-rohan-ad72e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhYigoFNNHDr3LkMUxGoTl1Xz0I9kXBTE',
    appId: '1:197971236822:ios:d4c604769cbd1306fc3677',
    messagingSenderId: '197971236822',
    projectId: 'project-rohan-ad72e',
    storageBucket: 'project-rohan-ad72e.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectRohan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhYigoFNNHDr3LkMUxGoTl1Xz0I9kXBTE',
    appId: '1:197971236822:ios:d4c604769cbd1306fc3677',
    messagingSenderId: '197971236822',
    projectId: 'project-rohan-ad72e',
    storageBucket: 'project-rohan-ad72e.firebasestorage.app',
    iosBundleId: 'com.example.flutterProjectRohan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXuwbpVjTtraQAnr7Fle6yrzKC2TpYvJY',
    appId: '1:197971236822:web:e5edc9a7b7676aa1fc3677',
    messagingSenderId: '197971236822',
    projectId: 'project-rohan-ad72e',
    authDomain: 'project-rohan-ad72e.firebaseapp.com',
    storageBucket: 'project-rohan-ad72e.firebasestorage.app',
    measurementId: 'G-HWPQCD12KM',
  );
}
